# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-02-28 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_auto_20220221_1231"),
    ]

    operations = [
        migrations.AlterField(
            model_name="elu",
            name="priority",
            field=models.IntegerField(db_index=True, default=500),
        ),
        migrations.AlterField(
            model_name="elu",
            name="role",
            field=models.CharField(
                choices=[
                    ("M", "Maire"),
                    ("CD", "Conseiller départemental"),
                    ("CR", "Conseiller régional"),
                    ("D", "Député"),
                    ("S", "Sénateur"),
                    ("DE", "Député européen"),
                    ("A", "Autre mandat"),
                ],
                db_index=True,
                max_length=2,
            ),
        ),
    ]
