name: Vérifications

on: push

jobs:
  checks:
    name: Vérifications
    runs-on: ubuntu-latest
    steps:
      - name: Copie de travail
        uses: actions/checkout@v2

      - name: Locale française
        run: |
          sudo apt-get install locales-all
          sudo localectl set-locale LANG=fr_FR.utf8

      - name: Installation de Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Installation des dépendances Python
        run: |
          python3 -m pip install -r requirements.txt -r requirements-dev.txt

      - name: Tests automatisés
        run: |
          pytest

      - name: Test de l’import des maires
        run: |
          python3 manage.py migrate

          wget --content-disposition https://www.data.gouv.fr/fr/datasets/r/2876a346-d50c-4911-934e-19ee07b0e503
          wget --content-disposition https://www.data.gouv.fr/fr/datasets/r/953465b8-35a3-4e54-89cd-0b9766503ff9
          wget https://www.insee.fr/fr/statistiques/fichier/6011070/ensemble.zip
          unzip ensemble.zip
          python manage.py import_maires rne-maires.csv mairies.csv donnees_communes.csv

      - name: Test de l’import des maires délégués
        run: |
          wget --content-disposition https://www.data.gouv.fr/fr/datasets/r/d5f400de-ae3f-4966-8cb6-a85c70c6c24a
          python manage.py import_elus --mandat=MD rne-cm.csv

      - name: Test de l’import des présidents de communautés de communes
        run: |
          wget --content-disposition https://www.data.gouv.fr/fr/datasets/r/41d95d7d-b172-4636-ac44-32656367cdc7
          python manage.py import_elus --mandat=CC rne-epci.csv

      - name: Test de l’import des conseillers départementaux
        run: |
          wget --content-disposition https://www.data.gouv.fr/fr/datasets/r/601ef073-d986-4582-8e1a-ed14dc857fba
          python manage.py import_elus --mandat=CD rne-cd.csv

      - name: Test de l’import des conseillers de Paris
        run: |
          python manage.py import_elus --mandat=CP rne-cm.csv

      - name: Test de l’import des conseillers régionaux
        run: |
          wget --content-disposition https://www.data.gouv.fr/fr/datasets/r/430e13f9-834b-4411-a1a8-da0b4b6e715c
          python manage.py import_elus --mandat=CR rne-cr.csv

      - name: Test de l’import des élus des collectivités à statut particulier
        run: |
          wget --content-disposition https://www.data.gouv.fr/fr/datasets/r/a595be27-cfab-4810-b9d4-22e193bffe35
          python manage.py import_elus --mandat=SP rne-ma.csv

      - name: Test de l’import des sénateurs
        run: |
          wget --content-disposition https://www.data.gouv.fr/fr/datasets/r/b78f8945-509f-4609-a4a7-3048b8370479
          python manage.py import_elus --mandat=S rne-sen.csv

      - name: Test de l’import des députés
        run: |
          wget --content-disposition https://www.data.gouv.fr/fr/datasets/r/1ac42ff4-1336-44f8-a221-832039dbc142
          python manage.py import_elus --mandat=D rne-dep.csv

      - name: Test de l’import des représentants au Parlement européen
        run: |
          wget --content-disposition https://www.data.gouv.fr/fr/datasets/r/70957bb0-f19f-40c5-b97b-90b3d4d71f9e
          python manage.py import_elus --mandat=DE rne-rpe.csv

      - name: Test de l’import des parrainages validés
        run: |
          wget https://presidentielle2022.conseil-constitutionnel.fr/telechargement/parrainagestotal.csv
          python manage.py import_parrainages parrainagestotal.csv --candidate="TAUBIRA Christiane"
